function settings = defaultSettings()
%DEFAULTSETTINGS 初期設定（ブラウザ版の defaultSettings と同じ）。Zernike項の大きさ terms も埋めて返す。
%   設定はブラウザ版の設定JSONと同じキー名の構造体で持つ（jsondecode で読んだ設定と同じ形）。
%   数の並びは列ベクトル、多項式の項の番号は 0 始まり（ブラウザ版と同じ番号）。

settings.map = struct( ...
    'source', 'generate', ...
    'shotWidthMm', 26, ...
    'shotHeightMm', 33, ...
    'offsetXmm', 13, ...
    'offsetYmm', 16.5, ...
    'validRadiusMm', 150, ...
    'scanPattern', 'serpentine', ...
    'serpentineStart', 'topLeft', ...
    'serpentineFirstScan', 'Up', ...
    'marks', struct('markNo', {1; 2; 3; 4}, 'x', {-12; 12; -12; 12}, 'y', {15.5; 15.5; -15.5; -15.5}));
% 初期のマップで、選べるShotの数が3領域でほぼそろう値（36・32・36個）
settings.zones = struct('innerRadiusMm', 95, 'outerRadiusMm', 135);
settings.evaluationData = struct( ...
    'waferCount', 100, ...
    'seed', 1, ...
    'distribution', 'uniform', ...
    'normalization', 'none', ...
    'lowOrderAmplitudeNm', 2, ...
    'highOrderAmplitudeNm', 0.5, ...
    'terms', [], ...
    'noiseSigmaXnm', 0.3, ...
    'noiseSigmaYnm', 0.3, ...
    'scanOffsetXnm', 0, ...
    'scanOffsetYnm', 0);
settings.evaluationData.terms = asc.defaultTermSettings(2, 0.5);
settings.model = struct( ...
    'termsX', (0:20)', ...
    'termsY', (0:20)', ...
    'flows', struct('howa', true, 'estimateThenHowa', true), ...
    'estimators', struct('rbfXY', true, 'rbfXYR', true, 'gpXY', true, 'gpXYR', true), ...
    'rbfKernel', 'tps', ...
    'rbfLambda', 0, ...
    'rbfShapeFactor', 2, ...
    'gpKernel', 'squaredExponential');
% 選んだShotでは、そのShotの有効なMarkをすべて測る。excludeIncompleteShots が true なら、
% Markが揃わない端のShot（有効半径の外にMarkがはみ出すShot）は選ばない
allMethods = struct('random', true, 'poisson', true, 'dOptimal', true, 'iOptimal', true, 'constrainedD', true, 'constrainedI', true);
settings.sampling = struct( ...
    'shotCount', 20, ...
    'excludeIncompleteShots', false, ...
    'draws', 30, ...
    'optimalStarts', 5, ...
    'seed', 1, ...
    'methods', allMethods);
settings.sweep = struct('startShots', 10, 'endShots', 60, 'stepShots', 10, 'draws', 10, 'methods', allMethods);
settings.constraints = struct( ...
    'center', struct('enabled', true, 'priority', 1), ...
    'scan', struct('enabled', true, 'hard', true, 'priority', 2, 'allocation', 'equal'), ...
    'quadrant', struct('enabled', true, 'hard', true, 'priority', 3, 'allocation', 'equal'), ...
    'zone', struct('enabled', true, 'hard', true, 'priority', 4, 'allocation', 'equal'), ...
    'softStrength', 0.5, ...
    'mandatoryShotIds', [], ...
    'excludedShotIds', []);
% mandatoryShotIds（強制計測Shot）・excludedShotIds（除外Shot）は Shot番号（ShotId）の文字の cell（{'30'; '45'}）。
% JSON から読むと cell の列になる（空は []）
end
